name: Bug Report
description: Report a bug in aiobsidian
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill in the details below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Minimal code example or steps to reproduce the behavior.
      placeholder: |
        ```python
        async with ObsidianClient("key") as client:
            await client.vault.get("note.md")  # fails with ...
        ```
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened. Include tracebacks if applicable.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: aiobsidian version
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      placeholder: "3.13"
    validations:
      required: true

  - type: input
    id: obsidian-plugin-version
    attributes:
      label: Obsidian Local REST API plugin version
      placeholder: "1.x.x"

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any additional information (OS, Obsidian version, etc.)
