"""Async Python client for Obsidian CLI and Local REST API plugin."""

from ._cli import ObsidianCLI
from ._client import ObsidianClient
from ._exceptions import (
    APIConnectionError,
    APIError,
    APINotFoundError,
    APIProtocolError,
    APIRequestError,
    APIStatusError,
    APITimeoutError,
    AuthenticationError,
    BinaryNotFoundError,
    CLIError,
    CLINotFoundError,
    CLIParseError,
    CLITimeoutError,
    CommandError,
    NotFoundError,
    ObsidianError,
)
from ._types import (
    ContentType,
    JsonValue,
    PatchOperation,
    PropertyType,
    PropertyValue,
    TargetType,
)
from .models import (
    Backlink,
    Bookmark,
    Command,
    DocumentMap,
    FileStat,
    Hotkey,
    MatchSpan,
    NoteJson,
    Plugin,
    SearchMatch,
    SearchResult,
    ServerStatus,
    Tag,
    Task,
    Versions,
)

__all__ = [
    "APIConnectionError",
    "APIError",
    "APINotFoundError",
    "APIProtocolError",
    "APIRequestError",
    "APIStatusError",
    "APITimeoutError",
    "AuthenticationError",
    "Backlink",
    "BinaryNotFoundError",
    "Bookmark",
    "CLIError",
    "CLINotFoundError",
    "CLIParseError",
    "CLITimeoutError",
    "Command",
    "CommandError",
    "ContentType",
    "DocumentMap",
    "FileStat",
    "Hotkey",
    "JsonValue",
    "MatchSpan",
    "NotFoundError",
    "NoteJson",
    "ObsidianCLI",
    "ObsidianClient",
    "ObsidianError",
    "PatchOperation",
    "Plugin",
    "PropertyType",
    "PropertyValue",
    "SearchMatch",
    "SearchResult",
    "ServerStatus",
    "Tag",
    "TargetType",
    "Task",
    "Versions",
]
